import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CMSContext } from "@/context";
import { AppProps } from "next/app";
import { Provider } from "@/client/apollo";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageProps,
}: {
  children: React.ReactNode;
  pageProps: AppProps;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Toaster />
          <CMSContext>{children}</CMSContext>
        </Provider>
      </body>
    </html>
  );
}
