import type { Metadata, NextPage } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CMSContext } from "@/context";
import { Toaster } from "react-hot-toast";
import { ReactElement, ReactNode } from "react";
import { Provider } from "@/client/apollo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Bit Fire",
    description: "Generated by create next app",
};
export type NextPageWithLayout<PageProps> = NextPage<PageProps> & {
    getLayout?: (page: ReactElement) => ReactNode;
};
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                    <Toaster />
                    <CMSContext>{children}</CMSContext>
                </Provider>
            </body>
        </html>
    );
}